apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
spec:
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.34.0
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: strimzi
  interval: 10m0s
