apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: identity-service
spec:
  releaseName: identity-service
  chart:
    spec:
      chart: podinfo
      version: "null"
      sourceRef:
        kind: HelmRepository
        name: ecr
        namespace: flux-system
  interval: 5m

