apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: contoso
resources:
  - namespace.yaml
  - ../../../apps/dev
patches:
  - target:
      kind: HelmRelease
      name: identity-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: contoso-identity-service
  - target:
      kind: HelmRelease
      name: processor-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: contoso-processor-service
  - target:
      kind: KafkaTopic
      name: topic-one
    patch: |-
      - op: replace
        path: /metadata/name
        value: contoso-topic